key_on:                     # The name of the event you wish to program a routine for
  ignore: key_on            # ignore means anyone who is set to receive the key_on event
                            # and has indeed received it will not receive new events until it is set again with listen:
  listen: key_off           # listen to key_off events
  parallel:                 # send out these two actions in parallel
    - start_recording       # tell someone to start recording
    - show_preview          # tell someone to show the preview (these two actions are mapped to a container in redis)
key_off:                    # Another event we are programming
  ignore: key_off           # Disable future key_off events from being propigated
  listen: key_on            # Enable key_on events
  break: key_on             # Break out of these steps if the key_on event happens and we are processing this routine
  parallel:                   # Kick off the following actions serially
    - stop_recording        # Stop recording footage
    - transfer_all_footage  # Transfer footage
    - kick_off_conversion   # Tell the backend to convert the footage to mp4 from h264
    - power_off             # Tells the GPIO container to off ourselves
lost_network:
  parallel:
    - start_recording
    - show_preview