version: '3'
services:
  redis:
   hostname: redis
   image: jrcichra/redisjson
  controller:
    hostname: controller
    image: jrcichra/smartcar_controller
    volumes:
      - "${PWD}/config.yml:/config.yml"
    depends_on:
      - redis
  dashcam:
   hostname: dashcam
   image: jrcichra/smartcar_dashcam
   volumes:
    - ~/recordings:/recordings
   depends_on:
      - controller
   command: "-rot 0 -fps 10 -h 1280 -v 720"
  gpio:
   hostname: gpio
   image: jrcichra/smartcar_gpio
   depends_on:
      - controller
  transfer:
   hostname: transfer
   image: jrcichra/smartcar_transfer
   volumes:
    - ~/recordings:/recordings
   depends_on:
      - controller
    command: "-nas_path ~/media/5tb/dashcam/recordings -nas_host 10.0.0.10 -nas_username pi -ci True"