version: '3'
services:
  redis:
   hostname: redis
   image: jrcichra/redisjson
  controller:
    hostname: controller
    image: jrcichra/smartcar_controller
    volumes:
      - "${PWD}/config.yml:/config.yml"
    depends_on:
      - redis
  dashcam:
   hostname: dashcam
   image: jrcichra/smartcar_dashcam
   volumes:
    - "${PWD}/recordings:/recordings"
    - "${PWD}/settings.yml:/settings.yml"
   depends_on:
      - controller
  gpio:
   hostname: gpio
   image: jrcichra/smartcar_gpio
   depends_on:
      - controller
  transfer:
   hostname: transfer
   image: jrcichra/smartcar_transfer
   volumes:
    - "${PWD}/recordings:/recordings"
    - "${PWD}/settings.yml:/settings.yml"
   depends_on:
      - controller
  cinas:
    hostname: cinas
    image: rastasheep/ubuntu-sshd
    volumes:
      - "${PWD}/nas:/recordings"