version: "3"
services:
  redis:
    environment:
      TZ: "America/New_York"
    hostname: redis
    image: jrcichra/redisjson
    restart: always
  controller:
    hostname: controller
    image: jrcichra/smartcar_controller_rpi
    restart: always
    volumes:
      - "${PWD}/config.yml:/config.yml"
    depends_on:
      - redis
  dashcam:
    environment:
      TZ: "America/New_York"
    hostname: dashcam
    image: jrcichra/smartcar_dashcam_rpi
    restart: always
    volumes:
      - "${PWD}/recordings:/recordings"
      - "${PWD}/settings.yml:/settings.yml"
    depends_on:
      - controller
    privileged: true
  gpio:
    environment:
      TZ: "America/New_York"
    hostname: gpio
    image: jrcichra/smartcar_gpio_rpi
    restart: always
    privileged: true
    depends_on:
      - controller
  transfer:
    environment:
      TZ: "America/New_York"
    hostname: transfer
    image: jrcichra/smartcar_transfer_rpi
    restart: always
    volumes:
      - "${PWD}/recordings:/recordings"
      - "${PWD}/settings.yml:/settings.yml"
    depends_on:
      - controller
