version: "3"
services:
  redis:
    environment:
      TZ: "America/New_York"
    hostname: redis
    image: jrcichra/redisjson
  controller:
    environment:
      TZ: "America/New_York"
    hostname: controller
    image: jrcichra/smartcar_controller
    volumes:
      - "${PWD}/config.yml:/config.yml"
    depends_on:
      - redis
  dashcam:
    environment:
      TZ: "America/New_York"
    hostname: dashcam
    image: jrcichra/smartcar_dashcam
    volumes:
      - "${PWD}/recordings:/recordings"
      - "${PWD}/settings.yml:/settings.yml"
    privileged: true
    depends_on:
      - controller
  gpio:
    environment:
      TZ: "America/New_York"
    hostname: gpio
    image: jrcichra/smartcar_gpio
    depends_on:
      - controller
  transfer:
    environment:
      TZ: "America/New_York"
    hostname: transfer
    image: jrcichra/smartcar_transfer
    volumes:
      - "${PWD}/recordings:/recordings"
      - "${PWD}/settings.yml:/settings.yml"
    depends_on:
      - controller
  cinas:
    environment:
      TZ: "America/New_York"
    hostname: cinas
    image: rastasheep/ubuntu-sshd
    volumes:
      - "${PWD}/nas:/recordings"
