version: '3'
services:
  redis:
   hostname: redis
   image: jrcichra/redisjson
  controller:
    hostname: controller
    image: jrcichra/smartcar_controller_rpi
    volumes:
      - "${PWD}/config.yml:/config.yml"
    depends_on:
      - redis
  dashcam:
   hostname: dashcam
   image: jrcichra/smartcar_dashcam_rpi
   volumes:
    - "${PWD}/recordings:/recordings"
    - "${PWD}/settings.yml:/settings.yml"
   privileged: true
   depends_on:
      - controller
  gpio:
   hostname: gpio
   image: jrcichra/smartcar_gpio_rpi
   depends_on:
      - controller
   privileged: true
  transfer:
   hostname: transfer
   image: jrcichra/smartcar_transfer_rpi
   volumes:
    - "${PWD}/recordings:/recordings"
    - "${PWD}/settings.yml:/settings.yml"
   depends_on:
    - controller